name: Go CI/CD

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17
        
    - name: Libraries
      run: sudo apt-get install -y libpcap-dev
      
    - name: Build
      run: go build -ldflags "-s -w"  -o heplify *.go
